from scrapy import Item, Field


class QuestionItem(Item):
    # _id = Field()
    url = Field()
    title = Field()
    content = Field()
    is_solved = Field()
    answer_count = Field()
    view_count = Field()
    vote_count = Field()
    answers = Field()
    tags = Field()
    source = Field()


class ArticleItem(Item):
    url = Field()
    title = Field()
    content = Field()
    tags = Field()
    source = Field()
    pub_date = Field()


class JobItem(Item):
    # _id = Field()
    city = Field()
    business_zones = Field()
    district = Field()
    company_id = Field()
    company_full_name = Field()
    company_short_name = Field()
    company_logo = Field()
    company_label = Field()
    company_size = Field()
    pub_time = Field()
    finance_stage = Field()
    industry_field = Field()
    industry_labels = Field()
    job_nature = Field()
    position_advantage = Field()
    position_id = Field()
    position_labels = Field()
    position_name = Field()
    salary = Field()
    job_type = Field()
    work_year = Field()
    education = Field()
    is_school_job = Field()
    job_detail = Field()
    job_address = Field()
    company_link = Field()
    source = Field()